#eureka:
#  client:
#    service-url:
#      defaultZone: http://172.16.41.107:8761/eureka
#  instance:
#    prefer-ip-address: true
#server:
#  port: 8080
#spring:
#  cache:
#    type: caffeine
#    caffeine:
#      spec: "expireAfterWrite=30s,expireAfterAccess=60s"
#  kafka:
#    consumer:
#      bootstrap-servers:
#        - 172.16.41.107:9092
#      group-id: tms-scheduler
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#
#    producer:
#      bootstrap-servers:
#        - 172.16.41.107:9092
#
#  application:
#    name: userman-service
#    version: 1.0.0
#  datasource:
#    driverClassName: org.postgresql.Driver
#    hikari:
#      idle-timeout: 5000
#      max-lifetime: 10000
#      maximum-pool-size: 10
#      minimum-idle: 3
#    initialization-mode: always
#    password: Acerespire!4
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/db_userman
#    username: postgres
#  partner-datasource:
#    url: jdbc:mysql://172.16.40.45:3306/bcm_prodv2
#    username: usr-read-useraccessmanagement
#    password: p@ssw0rd
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      read-only: true
#  jpa:
#    #    open-in-view: false
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: false
#    show-sql: true
#  output:
#    ansi:
#      enabled: ALWAYS
#minio:
#  url: http://172.16.41.103
#  port: 9000
#  access_key: Q5s0jJ3OBC6moQ1th1OQ
#  secret_key: iaXkLIlln09loCYK6oyQCJzPnBiKA23yQBYReqS8
#  bucket: "test-sda"
#baseUrl: http://localhost:8080/
#keycloak:
#  auth-server-url: https://dev-auth.gmf-aeroasia.co.id/auth
#  realm: master
#  resource: admin-cli
#  username: "782659"
#  password: "Aeroas1@59"